### 이슈 생성
POST localhost:8080/api/issues
Content-Type: application/json

{
  "projectId": 1,
  "title": "issueA",
  "description": "this is issueA",
  "assigneeIds": [1],
  "labelIds": [1],
  "startDate": "2025-02-06",
  "endDate":  "2025-03-03"
}

### 이슈 조회
GET localhost:8080/api/issues/1
Content-Type: application/json
