### 라벨 생성
POST localhost:8080/api/labels
Content-Type: application/json

{
  "userId": 1,
  "name": "12345"
}

### 라벨 조회
GET localhost:8080/api/labels
Content-Type: application/json

### 라벨 수정
PATCH localhost:8080/api/labels/1
Content-Type: application/json

{
  "userId": 1,
  "name": "modified LabelName"
}

### 라벨 삭제
DELETE localhost:8080/api/labels/1
Content-Type: application/json

{
  "userId": 1,
  "name": "modified LabelName"
}