### 프로젝트 생성
POST localhost:8080/api/projects
Content-Type: application/json

{
  "managerId": 1,
  "title": "projectA",
  "description": "this is projectA"
}

### 프로젝트 조회
GET localhost:8080/api/projects/1
Content-Type: application/json