### 프로젝트 생성
POST localhost:8080/api/projects
Content-Type: application/json

{
  "managerId": 1,
  "title": "projectA",
  "description": "this is projectA"
}

### 프로젝트 조회
GET localhost:8080/api/projects/1
Content-Type: application/json


### 이슈 생성
POST localhost:8080/api/projects/1/issues
Content-Type: application/json

{
  "title": "issueA",
  "description": "this is issueA",
  "assigneeIds": [1],
  "labelIds": [4],
  "startDateTime": "2025-02-06T12:30:00.000Z",
  "endDateTime":  "2025-03-03T12:30:00.000Z"
}

### 이슈 조회
GET localhost:8080/api/issues/1
Content-Type: application/json



### 라벨 생성
POST localhost:8080/api/labels
Content-Type: application/json

{
  "name": "labelD"
}

### 라벨 조회
GET localhost:8080/api/labels
Content-Type: application/json

### 라벨 수정
PATCH localhost:8080/api/labels/1
Content-Type: application/json

{
  "name": "modified LabelName"
}

### 라벨 삭제
DELETE localhost:8080/api/labels/2
Content-Type: application/json