### 프로젝트 생성
POST localhost:8080/api/projects
Content-Type: application/json

{
  "managerId": 1,
  "title": "projectA",
  "description": "this is projectA"
}

### 이슈 생성
POST localhost:8080/api/projects/1/issues
Content-Type: application/json

{
  "title": "issueA",
  "description": "this is issueA",
  "assigneeIds": [1, 2]
}

### 이슈 조회
GET localhost:8080/api/issues/1
Content-Type: application/json
